### ISSUE TITLE
Fee Handler integration testing

### ISSUE THREAD

**Issue by BennyOptions** [balancednetwork/balanced-contracts#419]
Deploy Fee Handler on testnet and ensure it works properly. Fee Handler was approved by vote with BIP6.

Fee Handler PR is #406

**Comment by simusud** [comment]
I have defined BIP6 on sejong testnet .
https://sejong.tracker.solidwallet.io/transaction/0xe09eeec09df074bc6905f87f9b3f915834e6705eda53fee4630af2f947e7458e
Casted a vote and approved it.
https://sejong.tracker.solidwallet.io/transaction/0x6ee87ab55c758741a145ee64e21c4bac96bd8ec180185622f5da27681e0ddcb6
And called evaluateVote method .
https://sejong.tracker.solidwallet.io/transaction/0x46508f8cc7028e6f8b944a2c320d67275ed97348d6c8f798a949059238b5c2db

BIP6 looks good.

Since the vote defined doesn't have any actions , the state after calling evaluateVote will be "Succeeded".

**Comment by simusud** [comment]
After merging fee handler updates, we are having problem while swapping the tokens. It says pool doesn't exist even though the pool exists in dex contract.

**Comment by Skyvell** [comment]
### Checklist settings

**Settings governance contract:**
- Register feehandler contract address.

**Settings dex contract**
- Set feehandler contract address.

**Settings feehandler contract**
- Set accepted dividends tokens.
- Set routes.
- Set fee-processing interval.

To me it sounds like there might be an issue with the routes in the feehandler contract. Just a guess though.
If the routes are incorrect/non-existent or there is a bug there, then it might cause the trades to fail since trades and feehandling is coupled.

**Comment by simusud** [comment]
i am setting route path for OMM fees as follows:
fromToken = OMM
toToken =   bnUSD
path = [ sICX, bnUSD]

Example:
fromToken = "cx683c78174c740c3c6215de0c3ead1fad024324d6"
toToken = "cx041714d034919c8456d3606f8766f0169e35cb8e"     
path = [ 
        "cx0e706eca3552a6e607095319f4ad8cea37e779d4", 
        "cx041714d034919c8456d3606f8766f0169e35cb8e"
        ]

Is there any issue while defining routes ? @Skyvell 
You can verify the routes i have defined in sejong :
https://sejong.tracker.solidwallet.io/contract/cx1e2ddb7bffd0bf8713878176f0754d6f89654a5b#readcontract

**Comment by Skyvell** [comment]
accepted_didivends_tokens looks fine.
fee_processing_interval looks fine.

You got the overall structure right for the route definition, but we want to convert to BALN, not bnUSD, right?

fromToken = OMM
toToken = BALN
path = [sICX, BALN]

Please let me know if you have more questions, or if defining the routes does not solve the issue.

**Comment by simusud** [comment]
Yeah, converting to BALN solved the issue . Thanks.
